name: automerge
on:
  pull_request:
    types:
      - opened
      - labeled
jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - uses: docker://agilepathway/pull-request-label-checker:latest
        with:
          all_of: automerge
          repo_token: ${{ secrets.GITHUB_TOKEN }}
            
      - id: automerge
        name: automerge
        uses: "pascalgn/automerge-action@v0.15.3"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          MERGE_LABELS: "automerge"
