name: Manually triggered workflow
on:
  push:
    branches:
      - '*'


jobs:
  log-github-info:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: set vars
        id: first_set
        run: |
          echo "::set-output name=build_number::2"
          echo "::set-output name=prev_build_number::1"

      - name: set vars again
        id: second_set
        run: |
          echo "::set-output name=build_number::3"
          echo "::set-output name=prev_build_number::2"
      
      - name: first run
        run: |
          sed -i 's/<string>${{steps.first_set.outputs.prev_build_number}}</string>/<string>${{steps.first_set.outputs.build_number}}</string>/' Info.plist
          cat Info.plist

      - name: second run
        run: |
          sed -i 's/<string>${{steps.second_set.outputs.prev_build_number}}</string>/<string>${{steps.second_set.outputs.build_number}}</string>/' Info.plist
          cat Info.plist
          