name: Manually triggered workflow
on:
  push:
    branches:
      - 'release-*'
    tags:
      - '*'


jobs:
  check:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v2
          with:
            fetch-depth: 0
            
        - name: Echo branch
          run: echo "${{ github.event.base_ref }}"

        - name: Get current branch
          id: check_step
          run: |
            echo "::set-output name=branch::${{ github.event.base_ref }}"
            echo "Branch is $branch."  
            
        - name: Get version from branch
          id: branch_version_step
          run: |
            branch_version=$(echo ${{ steps.check_step.outputs.branch }} | cut -d- -f2)
            echo "::set-output name=branch_version::$branch_version"
            echo "branch_version is $branch_version."
            
        - name: Get version from tag
          id: tag_version_step
          if: ${{ github.ref_type == 'tag' }}
          run: |
            tag_version=$(echo ${{ github.ref_name }} | cut -d- -f2)
            echo "::set-output name=tag_version::$tag_version"
            echo "tag_version is $tag_version."
            
          # Verify branch name match version of tag pushed
        - name: Verify params for submit build
          if: ${{ github.ref_type == 'tag' }}
          run: |
            [[ $tag_version = $branch_version ]] && exit 0 || exit 1;

  log-github-info:
    runs-on: ubuntu-latest
    needs: check
    steps:
      - run: echo fuck
