name: Manually triggered workflow
on:
  push:
    branches:
      - 'release-*'
    tags:
      - '*'


jobs:
  log-github-info:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ github.ref }} ${{ github.ref_name }}
