name: Manually triggered workflow
on:
  push:
    branches:
      - '*'


jobs:

  log-github-info:
    runs-on: macOS-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: set vars
        id: first_set
        run: |
          echo "::set-output name=build_number::2"
      
      - name: first run
        run: |
          plutil -replace CFBundleVersion -string ${{steps.first_set.outputs.build_number}} Info.plist
          cat Info.plist