name: Manually triggered workflow
on:
  push:
    branches:
      - '*'


jobs:
  log-github-info:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: |
          sed -i 's/VERSION_NUMBER/1.0.3/' example.txt
          cat example.txt
