name: Manually triggered workflow
on: workflow_dispatch

jobs:
  slackNotification:
    name: Slack Notification
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Slack Notification
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_CHANNEL: deployments
        SLACK_COLOR: ${{ job.status }}
        SLACK_ICON: https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png
        SLACK_MESSAGE: ${{ github.repository }} deploying to dev
        SLACK_TITLE: ${{ github.repository }} deploying to dev
        SLACK_USERNAME: github
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
